# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.api.references_api import ReferencesApi  # noqa: E501
from er.rest import ApiException


class TestReferencesApi(unittest.TestCase):
    """ReferencesApi unit test stubs"""

    def setUp(self):
        self.api = ReferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ref_get(self):
        """Test case for ref_get

        """
        pass

    def test_references_get(self):
        """Test case for references_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
