# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.models.program_array import ProgramArray  # noqa: E501
from er.rest import ApiException


class TestProgramArray(unittest.TestCase):
    """ProgramArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgramArray(self):
        """Test ProgramArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = er.models.program_array.ProgramArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
