# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.models.upload_body import UploadBody  # noqa: E501
from er.rest import ApiException


class TestUploadBody(unittest.TestCase):
    """UploadBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadBody(self):
        """Test UploadBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = er.models.upload_body.UploadBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
