# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.api.status_api import StatusApi  # noqa: E501
from pprint import pprint
from er.rest import ApiException

class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = StatusApi()  # noqa: E501
        self.api.api_client.configuration.host = "http://er.com:8082/v2"

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        """
        api_response = self.api.status_get()
        pprint(api_response)

    def test_status_put(self):
        """Test case for status_put

        """
        body = er.StatusBody(state='Executing')
        pprint(body)
        ret = self.api.status_put(body)


if __name__ == '__main__':
    unittest.main()
