# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.api.programs_api import ProgramsApi  # noqa: E501
from er.rest import ApiException

from pprint import pprint
import logging


class TestProgramsApi(unittest.TestCase):
    """ProgramsApi unit test stubs"""

    def setUp(self):
        self.api = ProgramsApi()  # noqa: E501
        self.api.api_client.configuration.host = "http://er.com:8082/v2"
        logger = logging.getLogger('er')
        logger.setLevel(logging.DEBUG)

    def tearDown(self):
        pass

    def test_programs_current_get(self):
        """Test case for programs_current_get

        """
        res = self.api.programs_get()
        # pprint(res)

    def test_programs_current_put(self):
        """Test case for programs_current_put

        """
        body = er.Program(name='process-robotics-test',arguments=[{}])
        pprint(body)
        res = self.api.programs_current_put(body)
        # pprint(res)

    def test_programs_get(self):
        """Test case for programs_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
