# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.api.help_api import HelpApi  # noqa: E501
from er.rest import ApiException


class TestHelpApi(unittest.TestCase):
    """HelpApi unit test stubs"""

    def setUp(self):
        self.api = HelpApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_datatypes(self):
        """Test case for get_datatypes

        """
        pass


if __name__ == '__main__':
    unittest.main()
