# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import er
from er.api.files_api import FilesApi  # noqa: E501
from er.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_file(self):
        """Test case for download_file

        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
