# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatatypeDictionary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'boolean': 'int',
        'double': 'int',
        'integer': 'int',
        'string': 'int'
    }

    attribute_map = {
        'boolean': 'Boolean',
        'double': 'Double',
        'integer': 'Integer',
        'string': 'String'
    }

    def __init__(self, boolean=None, double=None, integer=None, string=None):  # noqa: E501
        """DatatypeDictionary - a model defined in Swagger"""  # noqa: E501
        self._boolean = None
        self._double = None
        self._integer = None
        self._string = None
        self.discriminator = None
        if boolean is not None:
            self.boolean = boolean
        if double is not None:
            self.double = double
        if integer is not None:
            self.integer = integer
        if string is not None:
            self.string = string

    @property
    def boolean(self):
        """Gets the boolean of this DatatypeDictionary.  # noqa: E501


        :return: The boolean of this DatatypeDictionary.  # noqa: E501
        :rtype: int
        """
        return self._boolean

    @boolean.setter
    def boolean(self, boolean):
        """Sets the boolean of this DatatypeDictionary.


        :param boolean: The boolean of this DatatypeDictionary.  # noqa: E501
        :type: int
        """

        self._boolean = boolean

    @property
    def double(self):
        """Gets the double of this DatatypeDictionary.  # noqa: E501


        :return: The double of this DatatypeDictionary.  # noqa: E501
        :rtype: int
        """
        return self._double

    @double.setter
    def double(self, double):
        """Sets the double of this DatatypeDictionary.


        :param double: The double of this DatatypeDictionary.  # noqa: E501
        :type: int
        """

        self._double = double

    @property
    def integer(self):
        """Gets the integer of this DatatypeDictionary.  # noqa: E501


        :return: The integer of this DatatypeDictionary.  # noqa: E501
        :rtype: int
        """
        return self._integer

    @integer.setter
    def integer(self, integer):
        """Sets the integer of this DatatypeDictionary.


        :param integer: The integer of this DatatypeDictionary.  # noqa: E501
        :type: int
        """

        self._integer = integer

    @property
    def string(self):
        """Gets the string of this DatatypeDictionary.  # noqa: E501


        :return: The string of this DatatypeDictionary.  # noqa: E501
        :rtype: int
        """
        return self._string

    @string.setter
    def string(self, string):
        """Sets the string of this DatatypeDictionary.


        :param string: The string of this DatatypeDictionary.  # noqa: E501
        :type: int
        """

        self._string = string

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatatypeDictionary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatatypeDictionary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
