# coding: utf-8

"""
    Enabled Robotics REST Interface

    REST Interface exposed by Enabled Robotics  # noqa: E501

    OpenAPI spec version: 0.1-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Program(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'arguments': 'list[ProgramSetting]',
        'name': 'str',
        'webhook': 'ProgramWebhook'
    }

    attribute_map = {
        'arguments': 'arguments',
        'name': 'name',
        'webhook': 'webhook'
    }

    def __init__(self, arguments=None, name=None, webhook=None):  # noqa: E501
        """Program - a model defined in Swagger"""  # noqa: E501
        self._arguments = None
        self._name = None
        self._webhook = None
        self.discriminator = None
        if arguments is not None:
            self.arguments = arguments
        self.name = name
        if webhook is not None:
            self.webhook = webhook

    @property
    def arguments(self):
        """Gets the arguments of this Program.  # noqa: E501


        :return: The arguments of this Program.  # noqa: E501
        :rtype: list[ProgramSetting]
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this Program.


        :param arguments: The arguments of this Program.  # noqa: E501
        :type: list[ProgramSetting]
        """

        self._arguments = arguments

    @property
    def name(self):
        """Gets the name of this Program.  # noqa: E501


        :return: The name of this Program.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Program.


        :param name: The name of this Program.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def webhook(self):
        """Gets the webhook of this Program.  # noqa: E501


        :return: The webhook of this Program.  # noqa: E501
        :rtype: ProgramWebhook
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this Program.


        :param webhook: The webhook of this Program.  # noqa: E501
        :type: ProgramWebhook
        """

        self._webhook = webhook

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Program, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Program):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
